/**
 * function: search
 * author  : wq
 * update  : 2019/8/1 14:44
 */
// 录入数据
export const UPDATE_RECORD_PARAM = 'UPDATE_RECORD_PARAM'
export const RECORD_PARAM_REPLACE = 'RECORD_PARAM_REPLACE'
export const RECORD_PARAMS_RESET = 'RECORD_PARAMS_RESET'
export const TEMPLATE_CONFIG_RESET = 'TEMPLATE_CONFIG_RESET'
export const TEMPLATE_CONFIG_REPLACE = 'TEMPLATE_CONFIG_REPLACE'
export const TEMPLATE_CONFIG_CHILDREN_RESET = 'TEMPLATE_CONFIG_CHILDREN_RESET'
export const TEMPLATE_CONFIG_CHILDREN_REPLACE = 'TEMPLATE_CONFIG_CHILDREN_REPLACE'
export const UPDATE_PARAMS_DEPENDENT_TREE = 'UPDATE_PARAMS_DEPENDENT_TREE'
export const PARAMS_DEPENDENT_TREE_RESET = 'PARAMS_DEPENDENT_TREE_RESET'
export const UPDATE_CHECKED_PARAM_ITEM = 'UPDATE_CHECKED_ITEM'
export const RESET_CHECKED_PARAM_ITEM = 'UPDATE_CHECKED_ITEM'
